Removed test for < 768 DH parameters

diff --git a/test/testssl b/test/testssl
--- a/test/testssl
+++ b/test/testssl
@@ -171,16 +171,17 @@ for protocol in TLSv1.2 SSLv3; do
     for cipher in `../util/shlib_wrap.sh ../apps/openssl ciphers "EDH+aRSA+$protocol:-EXP" | tr ':' ' '`; do
       test_cipher $cipher $protocol
     done
-    echo "testing connection with weak DH, expecting failure"
-    if [ $protocol = "SSLv3" ] ; then
-      $ssltest -cipher EDH -dhe512 -ssl3
-    else
-      $ssltest -cipher EDH -dhe512
-    fi
-    if [ $? -eq 0 ]; then
-      echo "FAIL: connection with weak DH succeeded"
-      exit 1
-    fi
+## test removed on purpose
+#    echo "testing connection with weak DH, expecting failure"
+#    if [ $protocol = "SSLv3" ] ; then
+#      $ssltest -cipher EDH -dhe512 -ssl3
+#    else
+#      $ssltest -cipher EDH -dhe512
+#    fi
+#    if [ $? -eq 0 ]; then
+#      echo "FAIL: connection with weak DH succeeded"
+#      exit 1
+#    fi
   fi
   if ../util/shlib_wrap.sh ../apps/openssl no-ec; then
     echo "skipping RSA+ECDHE tests"
